astra-cql-store: # can be read from environment
  secure-connection-bundle-base64: base64value
  gateway-user: user
  gateway-password: password
scylla-cql-store:
  hosts:
    - host1
    - host2
  port: ""
  user: ""
  password: ""
  local-dc: ""
cql-store-type: astra
failure-rate-base-delay: 100ms
failure-rate-max-delay: 1s
rate-limit-elements-per-second: 10
rate-limit-elements-burst: 100
workers: 10
log-level: "INFO"
bind-port: 8080
