// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "ESD Support",
            "email": "esdsupport@ecco.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/algorithm/v1.2/complete/{algorithmName}/requests/{requestId}": {
            "post": {
                "description": "Commits the run result to the checkpoint store and transitions the state to COMPLETED",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/plain",
                    "text/html"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Completes the provided Nexus algorithm run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request id of the run to complete",
                        "name": "algorithmName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request id of the run to complete",
                        "name": "requestId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Run result",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AlgorithmResult"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AlgorithmResult": {
            "type": "object",
            "properties": {
                "errorCause": {
                    "description": "Failure cause, if any.",
                    "type": "string"
                },
                "errorDetails": {
                    "description": "Failure details, if any.",
                    "type": "string"
                },
                "resultUri": {
                    "description": "URL to download results.",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/algorithm/v1.2",
	Schemes:          []string{},
	Title:            "Nexus Receiver API",
	Description:      "Nexus Receiver API specification. All Nexus supported clients conform to this spec.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
